### ISSUE TITLE
Getting this error?

### ISSUE THREAD

**Issue by reliefs** [basti2342/retweet-bot#12]
Hi why am i getting this error?

No savepoint found. Trying to get as many results as possible.
Traceback (most recent call last):
  File "C:\twitterbot\bot.py", line 44, in <module>
    for status in timelineIterator:
  File "C:\Python27\lib\site-packages\tweepy\cursor.py", line 197, in next
    self.current_page = self.page_iterator.next()
  File "C:\Python27\lib\site-packages\tweepy\cursor.py", line 108, in next
    data = self.method(max_id=self.max_id, parser=RawParser(), *self.args, **self.kargs)
  File "C:\Python27\lib\site-packages\tweepy\binder.py", line 245, in _call
    return method.execute()
  File "C:\Python27\lib\site-packages\tweepy\binder.py", line 229, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Twitter error response: status code = 429
[Finished in 1.0s with exit code 1]
[shell_cmd: python -u "C:\twitterbot\bot.py"]
[dir: C:\twitterbot]

**Comment by basti2342** [comment]
Hey,

check https://dev.twitter.com/overview/api/response-codes:

> 429
> Returned in API v1.1 when a request cannot be served due to the application’s rate limit having been exhausted for the resource. See Rate Limiting in API v1.1.
