### ISSUE TITLE
unable to execute

### ISSUE THREAD

**Issue by arpitnot4u** [basti2342/retweet-bot#8]
the following are my logs:

root@ft2:~/t2/retweet-bot# python retweet.py
No savepoint found. Trying to get as many results as possible.
Traceback (most recent call last):
  File "retweet.py", line 44, in <module>
    for status in timelineIterator:
  File "/usr/local/lib/python2.7/dist-packages/tweepy/cursor.py", line 197, in next
    self.current_page = self.page_iterator.next()
  File "/usr/local/lib/python2.7/dist-packages/tweepy/cursor.py", line 108, in next
    data = self.method(max_id=self.max_id, parser=RawParser(), *self.args, **self.kargs)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/binder.py", line 239, in _call
    return method.execute()
  File "/usr/local/lib/python2.7/dist-packages/tweepy/binder.py", line 223, in execute
    raise TweepError(error_msg, resp)
tweepy.error.TweepError: {"errors":[{"message":"Rate limit exceeded","code":88}]}
root@ft2:~/t2/retweet-bot#

**Comment by basti2342** [comment]
Hi arpitnot4u,

as the error message states, your rate limit is exceeded. You can only perform a limited number of requests:
> Search will be rate limited at 180 queries per 15 minute window for the time being

Source: https://dev.twitter.com/rest/public/rate-limiting

Please adjust your retweet.py calls accordingly (crontab, sleep, ..) and consider other applications/scripts using API credentials.

Regards,
basti2342

**Comment by arpitnot4u** [comment]
Hi,

I'm executing this code for the first time with no last save point and hence as Line 37 in retweet.py ( https://github.com/basti2342/retweet-bot/blob/master/retweet.py#L37 ) says "No savepoint found. Trying to get as many results as possible."

Hence I guess in this case retweet.py should limit the number of calls.

Or kindly let me know the alternative.

**Comment by hippieshaman** [comment]
Hello, I'm having the same issue, and there is no information on how to stop the script before it hits the limit and iterate through what it already got. Trying to start it for the first time, no savefile.

**Comment by sciurus0** [comment]
You might consider noting in the description that this project is not compatible with Python 3.*

**Comment by dreameruk** [comment]
Exactly same issue as above ^ 

Did anyone resolve this? 

No savepoint found. Trying to get as many results as possible.
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:100: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "retweet.py", line 44, in <module>
    for status in timelineIterator:
  File "/usr/local/lib/python2.7/dist-packages/tweepy/cursor.py", line 197, in next
    self.current_page = self.page_iterator.next()
  File "/usr/local/lib/python2.7/dist-packages/tweepy/cursor.py", line 108, in next
    data = self.method(max_id=self.max_id, parser=RawParser(), *self.args, **self.kargs)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/binder.py", line 243, in _call
    return method.execute()
  File "/usr/local/lib/python2.7/dist-packages/tweepy/binder.py", line 227, in execute
    raise TweepError(error_msg, resp)
tweepy.error.TweepError: {"errors":[{"message":"Rate limit exceeded","code":88}]}

**Comment by reliefs** [comment]
same problem here can we resolve this?

**Comment by maitrey0da** [comment]
same problem here too

**Comment by basti2342** [comment]
I have no idea how we should limit the calls. If you have one, please propose it. Until then we will run into the rate limit.
